# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-04-06 09:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lkft', '0015_auto_20210211_1719'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportproject',
            options={'permissions': (('view_eap_projects', 'Can see available eap projects'), ('view_benchmark_projects', 'Can see available benchmark projects'))},
        ),
    ]
