# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-02-16 03:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lkft', '0015_auto_20210211_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestFailure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('stacktrace', models.TextField(blank=True, null=True)),
                ('testcase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lkft.TestCase')),
            ],
        ),
        migrations.CreateModel(
            name='TestSuite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('abi', models.CharField(max_length=16, null=True)),
                ('done', models.BooleanField(default=False)),
                ('number_pass', models.IntegerField(default=0)),
                ('number_total', models.IntegerField(default=0)),
                ('report_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lkft.ReportJob')),
            ],
        ),
        migrations.AddField(
            model_name='testcase',
            name='failure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='failure_details', to='lkft.TestFailure'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='testsuite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lkft.TestSuite'),
        ),
    ]
