# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-02-16 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lkft', '0016_auto_20210216_0305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testfailure',
            name='testcase',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='failure',
        ),
        migrations.AddField(
            model_name='testcase',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testcase',
            name='stacktrace',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='TestFailure',
        ),
    ]
