# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-04-07 08:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lkft', '0017_reportproject_is_public'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportproject',
            options={'permissions': (('view_eap_projects', 'Can see available eap projects'), ('view_benchmark_projects', 'Can see available benchmark projects'), ('admin_projects', 'Can do operations on the project, like job resubmission, job cancellation, build cancellation'))},
        ),
    ]
