# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-02-17 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lkft', '0018_auto_20210217_0529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='result',
            field=models.CharField(max_length=64),
        ),
    ]
