# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-04-08 09:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lkft', '0019_reportbuild_metadata_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportbuild',
            name='ci_build',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ci_build', to='lkft.CiBuild'),
        ),
        migrations.AlterField(
            model_name='reportbuild',
            name='ci_trigger_build',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trigger_build', to='lkft.CiBuild'),
        ),
        migrations.AlterField(
            model_name='reportbuild',
            name='kernel_change',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lkft.KernelChange'),
        ),
    ]
