# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-04-09 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lkft', '0020_auto_20210408_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportjob',
            name='finished_successfully',
            field=models.BooleanField(default=False),
        ),
    ]
