# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-04-12 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lkft', '0022_auto_20210409_0608'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportbuild',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
