# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-04-13 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lkft', '0024_reportproject_is_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportjob',
            name='fetched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportjob',
            name='parent_job',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reportjob',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
