# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-04-30 10:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lkft', '0026_reportjob_environment'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSuite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('abi', models.CharField(max_length=16, null=True)),
                ('done', models.BooleanField(default=False)),
                ('number_pass', models.IntegerField(default=0)),
                ('number_total', models.IntegerField(default=0)),
                ('report_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lkft.ReportJob')),
            ],
        ),
        migrations.AddField(
            model_name='testcase',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testcase',
            name='stacktrace',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kernelchange',
            name='reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='kernelchange',
            name='trigger_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='result',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='suite',
            field=models.CharField(max_length=256),
        ),
        migrations.AddField(
            model_name='testcase',
            name='testsuite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lkft.TestSuite'),
        ),
    ]
