# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-06-14 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lkft', '0027_auto_20210430_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='job_id',
            field=models.CharField(db_index=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='lava_nick',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='name',
            field=models.CharField(db_index=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='result',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='suite',
            field=models.CharField(db_index=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='name',
            field=models.CharField(db_index=True, max_length=256),
        ),
    ]
